### ISSUE TITLE
♻️ Upgrade all package dependencies

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#100]
Cc: @pierssinclairssw @adamcogan @AttackOnMorty 

Hi @ozairashfaqueSSW 

### Pain

In the last **yarn outdated** run, 3 packages required major backward-incompatible updates

### Tasks

- [x] Update all minor and patch versions
- [ ] ~~Update @mdx-js/mdx @mdx-js/react packages~~ (Not compatible with gatsby, see #109)
- [x] Update dotenv package to latest version
- [x] Update fontawesome package to latest version

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/152703006-557ae745-9ab4-44f7-bf55-d996a1bde72f.png)
**Figure: Update all the packages**

![image](https://user-images.githubusercontent.com/96504411/153332526-02b2a581-1978-4e73-9cb0-47f79801af80.png)
**Figure: Update all packages before production, @mdx-js/mdx and react cannot be updated:https://github.com/gatsbyjs/gatsby/issues/34706**

Thanks!

**Comment by ozair-ashfaque** [comment]
> Update dotenv package to latest version

Previous version was v14 and latest is v16. The changes in new version are as follow:
https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md
![image](https://user-images.githubusercontent.com/96504411/152715785-ea501582-bdfa-455c-af3c-935bb36d3cd6.png)
**Figure: 2 new changes added in dotenv**

**Comment by ozair-ashfaque** [comment]
> Update @mdx-js/mdx package to latest version
> Update @mdx-js/react package to latest version

gatsby-plugin-mdx is not compatible with v2 of @mdx-js/mdx and @mdx-js/react. We cannot update the packages to v2 untill they are compatible by gatsby-plugin-mdx
https://github.com/gatsbyjs/gatsby/issues/34706
![image](https://user-images.githubusercontent.com/96504411/152716734-5827cb70-3678-4bc9-acdf-2fe2254e8f73.png)
**Figure: LekoArts mention in the comment gatsby-plugin-mdx is not compatible with v2 of @mdx-js/mdx and @mdx-js/react**

**Comment by ozair-ashfaque** [comment]
yarn outdated packages are as follow:
![image](https://user-images.githubusercontent.com/96504411/152717147-451c6d38-1c09-41fa-86b2-b97195880c72.png)
**Figure: Only 2 packages remaining for update to latest version but not yet supported by gatsby-plugin-mdx**

**Comment by AttackOnMorty** [comment]
Created another issue for updating @mdx-js packages. Refer to #109
