### ISSUE TITLE
✨Add build number on the footer

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#101]
Cc: @AttackOnMorty @pierssinclairssw @adamcogan 

Hi @ozairashfaqueSSW 
  
### Pain

At the moment, the website's latest deployment links to Production - Deploy Gatsby but does not display the current deployment build number.
### Suggested Solution

The website should link to [Build](https://github.com/SSWConsulting/SSW.Website/actions/workflows/build.yml) and show the current build number.
### Tasks

- [x] Remove link to Production - Deploy Gatsby
- [x] Add link to [Build](https://github.com/SSWConsulting/SSW.Website/actions/workflows/build.yml)
- [x] Add current [Build number](https://github.com/SSWConsulting/SSW.Website/actions/workflows/build.yml)

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/152448768-53998043-248a-4550-be0b-c85869d451e1.png)
**Figure: Add new link to Build and add its current number**

![image](https://user-images.githubusercontent.com/96504411/152448872-dbdb25ef-77c4-46c6-94a8-b54aa69783f7.png)
**Figure: SSW rules shows current build number and links to build**

Thanks!

**Comment by AttackOnMorty** [comment]
Add last deployed time and build number. Didn't create a PR cos this needs frequent tests in the pipeline. 
- [x] @ozairashfaqueSSW Please have a look at these commits

![image](https://user-images.githubusercontent.com/37203901/153822719-290c2dcb-283a-43b7-a2d2-7c5865cb74db.png)
**Figure: Commits**

![image](https://user-images.githubusercontent.com/37203901/153822592-7de0816a-9973-47e0-b85f-0eff666178af.png)
**Figure: Current footer**
