### ISSUE TITLE
✨Add Linktree 

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#121]
Cc: @AttackOnMorty  @pierssinclairssw @adamcogan 

To myself,
  
### Pain

Add Linktree to the website after production to create the customizable page, that houses all the important links.
### Suggested Solution

Check how Linktree is implemented for [SSWConsulting](https://linktr.ee/SSWConsulting)
### Tasks

- [ ] Investigate how to implement Linktree 
- [ ] Implement the Linktree
- [ ] Check no link is broken

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/155425605-8cbf7a01-9da1-4913-9262-06010cba6912.png)
**Figure: Linktree has been implemented in [SSWConsulting](https://linktr.ee/SSWConsulting)**
Thanks!
