### ISSUE TITLE
✨ Add Google Signals

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#122]
Cc: @AttackOnMorty @pierssinclairssw @adamstephensen 

To Myself,
  
### Pain

This is related to issue #89. As per conversation with @adamcogan and  @camillars, need to add [Google Signals](https://support.google.com/analytics/answer/9445345?hl=en#zippy=%2Cin-this-article) in marketing tools.

### Tasks

- [ ] Investigate how to configure Google Signal
- [ ] Implement Google Signal
- [ ] Verify the data
- [ ] Check it by Camilla

Thanks!
