### ISSUE TITLE
✨Add mobile menu

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#123]
Cc: @AttackOnMorty @pierssinclairssw @adamcogan 

To Myself,
  
### Pain

Currently, the mobile menu is not added/working on the current website.
### Tasks

- [x] Investigate how to update MegaMenu
- [x] Follow instructions on [SSW.MegaMenu/README.md](https://github.com/SSWConsulting/SSW.MegaMenu/blob/main/README.md)
- [x] Implement the MegaMenu
- [x] Check mobile menu is working

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/155624433-757361c5-a702-4c06-8d99-869fe90fa425.png)
**Figure: SSW old website has menu for mobile view, it needs to add on SSW new website**
Thanks!

**Comment by ozair-ashfaque** [comment]
Done - see
![2022-03-02_13-55-08](https://user-images.githubusercontent.com/96504411/156286284-90f7cf37-d2fb-4e02-95bc-17d2acd1f6c5.gif)
**Figure: Mobile menu is working fine**
