### ISSUE TITLE
👷DevOps - Deploy Azure Front Door Standard to Staging

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#128]
Cc: @adamcogan @pierssinclairssw @AttackOnMorty 

To Myself,
  
### Pain

We need to implement Azure Front Door Standard on the SSW Subscription
### Suggested Solution

Follow the Microsoft documentation for [Azure Front Door Standard/Premium](https://docs.microsoft.com/en-us/azure/frontdoor/standard-premium/). 

### Tasks

- [x] Investigate how to implement Azure Front Door
- [x] Implement Azure Front Door in Staging
- [x] Proof of concept that Front Door reaches 2 separate dummy static sites based off URL route

### More Information

Azure Front Door Standard features ($64.93 /month) are:
- CDN included
- Static and dynamic content acceleration
- Global load balancing
- SSL offload
- Domain and certificate management
- Enhanced traffic analytics
- Basic Security capabilities included (WAF)
- Layer 7 routing (The feature we need)
- URL rewrite
- Rules Engine

Thanks!

**Comment by lukecookssw** [comment]
Azure Front Door is now live in the staging environment.
