### ISSUE TITLE
✨Consulting Template - Technologies component

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#141]
Cc: @lukecookssw @pierssinclairssw @adamcogan @AttackOnMorty 

To Myself,
  
### Pain

The current technologies component is hard-coded.  To make it easier to edit/add new technologies and to reduce code duplication we want to dynamically render them from the [content repo](https://github.com/SSWConsulting/SSW.Website.Content). 

### Tasks
 
- #### Research Work
    - [x] Research how to implement technologies component  
    
- #### Create pages from data Programatically
    - [x] Create pages using gatsby-node.js 
    - [x] Render consulting pages from consulting directory of [content repo](https://github.com/SSWConsulting/SSW.Website.Content)
    - [x] Filtered the rest directories
    - [x] Refactor consulting template and delete mdx.slug
    
- #### Render technologies component
    - [x] Create technologies directory for mdx content and images
    - [x] Create hook for gatsby static query to grab all technologies node
    - [x] Filter nodes using specified keys
    - [x] Create generic layout for technology component
    - [x] Render technologies component from technologies directory of [content repo](https://github.com/SSWConsulting/SSW.Website.Content)

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/162671420-6afb21b7-d3e4-4d28-abdb-5319772ae642.png)
**Figure: Other Techonologies on [ssw consulting pages](https://www.ssw.com.au/ssw/Consulting/Web-Applications.aspx)** 
Thanks!

**Comment by ozairashfaqueSSW** [comment]
All done - see
![technologies](https://user-images.githubusercontent.com/96504411/164588376-27934ea0-9597-48ab-89d2-f8e4af629b7d.gif)

**Comment by ozair-ashfaque** [comment]
Done - see
![technologies](https://user-images.githubusercontent.com/96504411/164588719-24a1b3c2-9a86-459d-88a4-00bcf802adc5.gif)
**Figure: Technologies components are generated dynamically**
