### ISSUE TITLE
✨ Add axios post method for creating lead in CRM

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#143]
Cc: @pierssinclairssw @adamcogan @lukecookssw 

To Myself,
  
### Pain

Currently, on the booking form when you try to book, it doesn't do anything. We need to update it so it uses axios to call the old website endpoint for creating a lead in CRM.

### Tasks

- [x] Add axios post method to endpoint of the old website
- [x] Test creating lead on [CRM](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entitylist&etn=lead&viewid=5a926b99-3a5f-df11-ae90-00155d2e3002&viewType=1039)
- [x] Redirect to Thankyou page after successful form submission

### Screenshots

![Image](https://user-images.githubusercontent.com/79821522/169725193-989d1e09-d0bc-4296-b23f-5bb70d591770.png)
**Figure: The Submit button on the booking form doesn't do anything**

Thanks!

**Comment by ozair-ashfaque** [comment]
> - [ ]  Test creating lead on [CRM](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entitylist&etn=lead&viewid=5a926b99-3a5f-df11-ae90-00155d2e3002&viewType=1039)

**Blocked: Azure Frontdoor is not updated with domain @kikibianc**
