### ISSUE TITLE
✨ Add SSW Web Forms site to Staging as an App Service

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#146]
Cc:

To myself,
  
### Pain

The old Web Forms site will still be required in the new production environment for some time. As we are building out the Staging environment to be a template for the future prod environment, we need the Web Forms app running in Azure and plugged into our Azure Front Door.

### Suggested Solution

Create a new Resource Group: SSW.WebFormsSite.Staging
Deploy the Web Forms project to an App Service inside this RG.
Create any related infrastructure the site needs (such as any SQL databases) as resources within this RG
Plug the App Service into SSWFrontDoorStaging with some routes.

### Tasks

- [x] Spin the Web Forms project up locally
- [x] Publish the app locally to file system
- [x] Create Azure RG and resources
- [x] Learn how to deploy Web Forms app to App Service
- [x] Manually deploy the Web Forms app (and any associated resources) to their created services
- [x] Add FrontDoor routes and test

### More Information

This is considered an Epic. As GitHub does not support task breakdowns per issue, we should treat each task as a separate child PBI.

**Comment by lukecookssw** [comment]
App Service is now live in Staging.
There are some niggling issues around both the static site and the web forms site fighting over the base path, which will need to be addressed in the next sprint.
