### ISSUE TITLE
Sub task - Consulting services filter

### ISSUE THREAD

**Issue by paulsmythssw** [SSWConsulting/zzSSW.Website#166]
Cc: @adamcogan @AttackOnMorty @pierssinclairssw @christianmorfordwaitessw @lukecookssw @tiagov8 

To Myself,
  
### Pain
Currently, the [Legacy Website](https://www.ssw.com.au/ssw/consulting/) has simple filter functionality to filter the consulting services. As per the conversation with @tiagov8, there is a need to implement the advanced filter functionality similar to the [SSW.People](https://www.ssw.com.au/people/)

### Suggested Solution

Investigate the implementation of People / role filter on [SSW.People repo](https://github.com/SSWConsulting/SSW.People)

### Tasks

- [ ] Investigate how the filter has been implemented on [SSW.People](https://www.ssw.com.au/people/)
- [ ] Design the mdx content on [SSW.Website.Content]() file as per requirement 
- [ ] Create helper functions if required
- [ ] Implement the filter

### Screenshots

![consulting-filter](https://user-images.githubusercontent.com/96504411/174715845-de5b48fa-4e50-4c62-9d5a-f3a9149de631.gif)
**Figure: Current behavior of filter on Legacy Website**

![people-filter](https://user-images.githubusercontent.com/96504411/174715896-62a18a70-048d-4f00-ae6c-07c7f2de9482.gif)
**Figure: Advance filter implemented on SSW People Website**

Thanks!
