### ISSUE TITLE
♻️ Chore - update critical dependencies

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#176]
Cc: @lukecookssw @pierssinclairssw 

Hi 

### Pain

There are 6 dependencies that are critically out of date.

### What code could be improved?

Each of the 6 dependencies should be updated and checked for compatibility.

### Tasks

- [x] Research changes for each of the dependencies
- [x] Update each dependency and check for any errors
- [x] Refactor any code necessary for the update

### Screenshots

![image](https://user-images.githubusercontent.com/71110132/167086322-1c264982-f415-4e23-9a19-67374e5dc512.png)
Figure: Out of date dependency list

Thanks!

**Comment by ozair-ashfaque** [comment]
Done - All major, minor, and security patches are updated.
![image](https://user-images.githubusercontent.com/96504411/167778912-2eb4ef6a-8b67-475e-83c9-33ac97547c13.png)
**Figure: React v18 has breaking changes, which will break the website and @mdx v2 are not yet supported by [Gatsby](https://github.com/SSWConsulting/SSW.Website/issues/100)**
