### ISSUE TITLE
Create FrontDoor redirect routes as IaC

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#178]
Cc:

To Myself,
  
### Pain

The AFD infrastructure needs to be established as IaC to be replicated across multiple environments. This includes the provisioning of the AFD resource, the configuration of its Origin Groups, Routes, Rulesets and Custom Domains.

### Tasks

- [x] Build the IaC workflow in development environment
- [x] Create a new SSW Repo - SSW.FrontDoor.IaC
- [x] Create two GitHub Environments - Staging and Production
- [x] Test IaC pipeline in Staging environment

Thanks!

**Comment by lukecookssw** [comment]
Bicep templates have been built and verified in Dev environment, however we cannot integrate them into staging/production until SysAdmins finish the staging AFD configuration to add the missing bits.

DONE:
AFD Resource
Origin Groups
Routes
Redirect rules

Missing:
Domain config (DNS zoning)
WAF policy config (missing basic WAF rules that should be there)

Once these are done, I can add them into the bicep template and we can integrate the IaC into staging.

**Comment by lukecookssw** [comment]
The redirect rules have been added in my local dev branch, but have not been merged yet as we need to wait until the content review is complete before rolling these rules out.
