### ISSUE TITLE
🟢 Subtask - reCAPTCHA

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#198]
Cc: @adamcogan @pierssinclairssw @lukecookssw @bigtony97 @paulsmythssw @kevinpho2022 @christoment 

To Myself,
  
### Pain

Currently, [legacy website](https://www.ssw.com.au/ssw/) is using reCAPTCHA to prevent spam and abuse from entering the site while submitting forms.
### Suggested Solution

- reCAPTCHA can be injected through GTM, but it is not a suggested solution as GTM requires [Server-side tagging](https://developers.google.com/tag-platform/tag-manager/server-side/intro#:~:text=Server%2Dside%20tagging%20is%20a,user%20activity%20wherever%20it%20happens.). As @christoment advised not to use GTM for recaptcha.
- Inject reCAPTCHA script into the forms 
### Tasks

- [x] Investigate how to implement reCAPTCHA
- [x] Implement reCAPTCHA into forms
- [x] Test the form

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/170408437-6d7c80e8-7f65-4d7a-9709-c924c8fa810b.png)
**Figure: reCAPTCHA prevents bots**
Thanks!

**Comment by ozair-ashfaque** [comment]
> - [ ] Test the form

**Blocked: domain is not updated in Azure Front door**
