### ISSUE TITLE
♻ Refactor technologies component

### ISSUE THREAD

**Issue by doueal** [SSWConsulting/zzSSW.Website#202]
Cc: @ozairashfaqueSSW @kevinpho2022 @bigtony97 @lukecookssw @pierssinclairssw 

To myself,

### Pain

The technology component needs to be more flexible to account for different types of content.

### Tasks

- [x] Remove the title from the hook query
- [x] Remove the title from the technologies React component
- [x] Move the title from frontmatter in all existing technologies MDX files
- [x] Make the title of the technologies section dynamic

### Screenshots

Thanks!
