### ISSUE TITLE
✨Consulting - Are You Stuck animation

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#212]
Cc:@tiagov8 @pierssinclairssw  @lukecookssw @adamcogan  

To Myself,
  
### Pain

Currently, Are-you-stuck consulting page does not have animation while changing from the Business to Developer tab and vice versa. There is a need to add animation while switching.
### Suggested Solution

It is better to create a custom hook for the animation to increase the reusability in other templates as well.
### Tasks

- [x] Investigate how to do that
- [x] Create an animation custom hook
- [x] Implement it for Are-you-stuck page
- [x] #213
- [x] Merge to main branch

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/174920467-16bf1653-e5c1-44d2-aa38-150760be8df8.png)
**Figure: Switching tab simply display the content**
Thanks!
