### ISSUE TITLE
♻️ Refactoring Content- Remove duplication of images in SSW.Website.Content

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#215]
Cc: @adamcogan @pierssinclairssw @lukecookssw @christianmorfordwaitessw 

To Myself,

### Pain

Currently, there is a duplication of images in the technologies and consulting components. All common assets/images should be provided from single shared source. 
### What code could be improved?

[Technology component](https://github.com/SSWConsulting/SSW.Website/blob/main/src/hooks/use-technology-mdx-data.tsx) [Technology hook](https://github.com/SSWConsulting/SSW.Website/blob/main/src/hooks/use-technology-mdx-data.tsx)  and config-node.js requires refactoring.
### Tasks

- [x] Investigate how to do it for [technologies](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/technologies), [legacy](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/legacy) and [consulting](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/consulting)
- [x] Add ImageUrlData.json file for mapping image urls and exactmatch keys 
- [x] Create ImageUrls node on config.node 
- [x] Create fileNode for caching images in gatsby-filesystem using urls of ImageUrls node from from [SSW.Website.Content](https://github.com/SSWConsulting/SSW.Website.Content/tree/main/assets/images/thumbs)
- [x] Check for any broken link and resolve it
- [x] Update [Technology hook](https://github.com/SSWConsulting/SSW.Website/blob/main/src/hooks/use-technology-mdx-data.tsx) 
- [x] Add new hook useAllImagesUrlData for getting all images
- [x] Added helper componennt ImageToUrl to match exact keys and getting related images

Thanks!

**Comment by ozair-ashfaque** [comment]
As per my conversation with @christoment and @christianmorfordwaitessw, there is a change in strategy. 
**Old Strategy**

- Previously, we were implementing a fallback strategy for different image types. But it was throwing a 404 error in the console while finding the correct type. 

**New Strategy**

- Add JSON file in [SSW.Website.Content]() mapped with valid image links and keywords similar to [SkillDataURL](https://github.com/SSWConsulting/SSW.People/blob/main/SkillUrlData.json)
- update [technology](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/technologies), [legacy](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/legacy) and [consulting](https://github.com/SSWConsulting/SSW.Website.Content/tree/staging/consulting) content
