### ISSUE TITLE
✨ Better design for 404 Page

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#219]
Cc: @adamcogan @lukecookssw @pierssinclairssw @tiagov8 

To Myself
  
### Pain

Currently, the legacy website [404 page](https://www.ssw.com.au/ssw/s) has less useability. Need to add a better UI for the page and content to keep the user interacted with website.
### Tasks

- [ ] Remove brackets on video all and link move to the right
- [ ] add an extra HR between the Logos and Content
- [ ] investigate why list style is not committed

### Screenshots

![image](https://user-images.githubusercontent.com/97079655/180372440-cb582fc9-3350-49e6-8b82-e8fde030f46f.png)
figure: current location of bracketed all videos link

![image](https://user-images.githubusercontent.com/97079655/180372322-f6cb5ac1-bf0b-4eb9-aa83-0d0deefc9643.png)
**figure: add extra hr**

![image](https://user-images.githubusercontent.com/97079655/180372742-cb52bdfc-d578-45e2-b8d4-f8162f99378d.png)
figure: list style was added previously 

Thanks!
