### ISSUE TITLE
♻️Fix the issue "Cannot find *.css module" in components

### ISSUE THREAD

**Issue by steven0x51** [SSWConsulting/zzSSW.Website#221]
Cc: @adamcogan @ozairashfaqueSSW @lukecookssw @pierssinclairssw 

To myself,

### Pain
Currently when components import .css module from same directory there will be errors:
 `Cannot find module './index.module.css' or its corresponding type declarations.ts(2307)`. 

### Tasks
- [x] Investigate the reason
- [x] Fix the issue
- [x] Merge to main

### Screenshots
![image](https://user-images.githubusercontent.com/41563445/177900923-05b2f2e5-bb5b-4bfe-abf2-f1ab81752eba.png)

Thanks!
