### ISSUE TITLE
✨ Build a POC for multilingual website content

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#250]
Cc: @JeanThirion @tiagov8 @wicksipedia @adamcogan 

Hi Jean,
  
### Pain

We are developing a European (French) website, and want to use a substantial amount of content from the existing Aussie site. However, all the content is written in English and stored in markdown files within GitHub. To manually translate (and maintain) every page is an enormous amount of work.

### Suggested Solution

Investigate the feasibility and - if possible - build a POC that demonstrates a method of deploying the Gatsby website to 2 separate static sites (Aussie and French), using a mix of automated content translation and manual translation overrides.

### Tasks

- [ ] Build a GitHub action that takes the content of [the markdown](https://github.com/SSWConsulting/SSW.Website.Content/blob/main/consulting/scrum/index.mdx) of the [Scrum page](https://www.ssw.com.au/ssw/Consulting/Scrum.aspx) and automatically translates it to French (excluding things such as filenames, keys, URLs, etc.)
- [ ] Generate a PR into a new (French) content repo with the Frenchified Scrum markdown file

Then for deployment, create a Gatsby build process that:
- [ ] Queries the French and English content repos
- [ ] Uses the French markdown to generate the static HTML for all pages that contain French content (in this case, just the Scrum page)
- [ ] Uses the English markdown to generate all other static HTML pages.

### More Information
This proposal does not include tagging individual pieces of content with metadata for auto vs manual translation. Instead, this can be handled when reviewing the Frenchified content PR, allowing native French speakers to review and modify the content before merging it in.

![French](https://user-images.githubusercontent.com/100659715/197934506-5b8988f7-98b8-4ad6-881c-f56a5bdc5f4e.png)
**Figure: suggested flow for the multilingual, GitHub CMS approach**

Thanks!
