### ISSUE TITLE
✨Azure Functions + Shared KeyVault Endpoints for all SSW.Websites and Microservices

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/zzSSW.Website#251]
Cc: @lukecookssw @pierssinclairssw 

Hi @danielmackay 
  
### Pain
Currently, the APIs needed to drive the newsletter, contact and events functionality on the website are couple to the old Webforms site.  As this site is to be decommissioned, we need to move these APIs out of this website.

### Suggested Solution
Move each APIs into their own Function App in Azure.  A shared KeyVault will need to be setup to store relevant secrets.  The APIs will also need to securely communicate with downstream APIs like Sharepoint

### Tasks

*News Letter API*
- [ ] Create new repo 
- [ ] Create new Function App
- [ ] Provision Function App via bicep
- [ ] Setup Pipelines
- [ ] Call downstream API

*Contact API*
- [ ] Create new repo 
- [ ] Create new Function App
- [ ] Provision Function App via bicep
- [ ] Setup Pipelines
- [ ] Call downstream API

*Events API*
- [ ] Create new repo 
- [ ] Create new Function App
- [ ] Provision Function App via bicep
- [ ] Setup Pipelines
- [ ] Call downstream API

*Shared KeyVault*
- [ ] Create new repo
- [ ] Provision KeyVault via bicep

*Old Website*
- [ ] Remove Newsletter API
- [ ] Call new Newsletter API
- [ ] Remove Contact API
- [ ] Call new Contact API
- [ ] Remove Event API
- [ ] Call new Event API

### More Information
- Old website can be found with Azure Dev Ops (there are two repos, so ensure you have the right one)
- Talk to @calumjs or @ozdemir-mehmet about CRM auth
