### ISSUE TITLE
♻️ Use the ssw.megamenu NPM package

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/zzSSW.Website#274]
Cc: @adamcogan @bradystroud 

Hi team,

### Pain

Currently, the SSW MegaMenu is being manually built and copied over to this repository for use.
https://github.com/SSWConsulting/SSW.MegaMenu/issues/9

### What code could be improved?

The SSW MegaMenu has recently been converted into an NPM package and can now be installed and imported as required.
https://www.npmjs.com/package/ssw.megamenu

### Tasks

- [x] Install and import the new MegaMenu NPM package
- [x] Update all code using the Menu with the new component
- [x] Remove all files related to the old menu

Thanks!

**Comment by KristenHu** [comment]
**Done** - Replaced the component and added the npm package
