### ISSUE TITLE
✨Setup - Initialize Gatsby project

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#3]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw 

To Myself
  
Adam has approved the rebuilding of the SSW Website using Gatsby and Typescript

### Tasks

- [x] Initialize a Gatsby Project with the name SSW Website
- [x] Ensure that Typescript is supported
- [x] Add the new Gatsby project to the repo

Thanks!
