### ISSUE TITLE
✨Setup - Configure project settings

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#4]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw 

To Myself
  
Cannot be completed until #4

### Tasks

- [x] Investigate required project settings
- [x] Add the projects settings to the project
- [x] Hook the Gatsby project to the Content repo

Thanks!
