### ISSUE TITLE
✨ Layout - Improve header and footer component v2

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#58]
Cc: @tkapa @ozairashfaqueSSW @pierssinclairssw @adamcogan @Hona @jimmidier 

To myself, 
  
### Pain

As per our conversation, will do the following changes. Thanks for your feedback.

### Tasks

For header:
- [x] Rename TopBar component to Header
- [x] Check Header container padding
- [x] Check Phone icon (flipped, size)
- [x] Check phone number font color
- [x] Make social media icons centered

For footer:
- [x] **FEEDBACK TO SSW** should link to the new issue page
- [x] Keep **SITEMAP** and **HEALTH CHECK**
   - Add GitHub issues links 
   - Move them to the right-bottom
   - Move **HEALTH CHECK** heart icon to the right
 - [x] Check divider between rows
 - [x] Check font size

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/147633485-f532cb73-8591-4daf-9eb9-0881a6d2875d.png)
![image](https://user-images.githubusercontent.com/37203901/147633487-18b8f8a2-9bbd-4774-a74f-6e6ec7676ade.png)
**Figure: Current header and footer**

Thanks!
