### ISSUE TITLE
♻️  Consulting Template - Extract reuseable componnets

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#60]
Cc: @tkapa @ozairashfaqueSSW @pierssinclairssw @adamcogan @Hona 

To myself,
  
### Pain

As per our conversations, will extract the following reusable components in consulting template.

### Tasks

- [x] Video background component
- [x] Booking button component
- [x] Components that have `dangerouslySetInnerHTML` attribute

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/147635718-93ebb139-069b-4b25-a3ec-34c389a9dd0a.png)
**Figure: Parts that can be resueable componnets**

Thanks!
