### ISSUE TITLE
✨ SEO - Add sitemap

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#63]
Cc: @tkapa @ozairashfaqueSSW @pierssinclairssw @adamcogan @Hona 

To myself,
  
### Pain

Add sitemap for better SEO

### Tasks

- [x] Generate sitemap by Gatsby plugin
- [ ] Implement sitemap page. Refer to https://www.ssw.com.au/ssw/MenuMap.aspx
- [ ] Update **SITEMAP** link on site footer

### More Information

- https://www.ssw.com.au/rules/rules-to-better-google-rankings/
- https://developers.google.com/search/docs/advanced/sitemaps/overview

### Screenshots
![image](https://user-images.githubusercontent.com/37203901/147729573-5aff8764-0edf-4fea-ade8-2812272103ac.png)
**Figure: SITEMAP on the footer**

Thanks!

**Comment by AttackOnMorty** [comment]
>  - [ ] Implement sitemap page. Refer to https://www.ssw.com.au/ssw/MenuMap.aspx
 
Blocked, move to the backlog. It should be implemented after deploying to the production cos the links in the sitemap page will be production links. Refer to implementation on the old website: [MenuMap.aspx](https://dev.azure.com/ssw2/SSW.Website/_versionControl?path=%24%2FSSW.Website%2Ftrunk%2FSSW.Website.WebUI%2FMenuMap.aspx&vc.GitRepositoryName=%24%2FSSW.Website&_a=contents&version=T)

Below are the steps we need to perform after deploying.
1. In [SSW.Website.Menu.json](https://github.com/SSWConsulting/SSW.Website.Menu.json), add a new file `menu-for-new-website.json` copied from `menu.json`
2. Update `menu-for-new-website.json`. Remove unimplemented page and update implemented page links
3. Implement sitemap page using data from `menu-for-new-website.json`

**Comment by camillars** [comment]
Hi @AttackOnMorty 

cc: @adamcogan 

Do we have an approximate date on when to expect this to be deployed to production?

Cheers,
Camilla
