### ISSUE TITLE
✨ Index Page - Add image Carousel v2

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#75]
Cc: @ozairashfaqueSSW @pierssinclairssw @adamcogan 

To myself,
  
### Pain

The image Carousel is not consistent with the old website.

### Tasks

- [ ] ~~The carousel indicators should be on the right~~ (as per our conversation, indicators in the middle looks fine)
- [x] Carousel indicators hover effect
- [x] Add image transition animation
- [x] Image links

### Screenshots
![image](https://user-images.githubusercontent.com/37203901/149078381-3b1b68b5-dcfb-45cd-9402-78261ac602d4.png)
Figure: Image carousel on [old website](https://www.ssw.com.au/ssw/)

Thanks!
