### ISSUE TITLE
✨ Index Page - Add SSW TV and Contact Us component

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#77]
Cc: @ozairashfaqueSSW @pierssinclairssw @adamcogan 

To myself,

### Tasks

- [x] Extract video component
- [x] Add SSW TV component
- [x] Investigate map component
- [x] Add Contact Us component

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/149079950-66bc24a6-41af-4f8a-a311-895eb06d6b5b.png)
**Figure: SSW TV and Contact Us component**

Thanks!

**Comment by ozair-ashfaque** [comment]
All done - see 
![image](https://user-images.githubusercontent.com/96504411/154191261-7ee60835-0c06-4641-a464-bc52c2301851.png)
**Figure: Tv video, contact us accordion and map is added**
