### ISSUE TITLE
✨  Index Page - Check the undercover stuff

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#84]
Cc: @ozairashfaqueSSW @pierssinclairssw @adamcogan 

To myself,
  
### Pain

The index page might not just be what we saw, we need to check whether there are any hidden features like Google Analytics.

### Tasks

- [x] Check the old website source code
- [x] Use Chrome or other tools to check

Thanks!

**Comment by AttackOnMorty** [comment]
Here is the investigation result. We need to implement the tools below.

## Analytics
- [ ] Google Analytics
- [ ] Google Ads Conversion Tracking
- [ ] Conversion Linker
- [ ] Facebook Pixel
- [ ] Hotjar
- [ ] HubSpot Analytics
- [ ] Linkedin Insight Tag 
- [ ] Azure Application Insight


## Advertising
- [ ] Google AdSense


## Tag managers
- [ ] Google Tag Manager


## Security 
- [ ] reCAPTCHA


## Miscellaneous
- [ ] Google Account Verification
- [ ] Facebook Domain Verification
- [ ] Vimeo Tracking
- [ ] Link Click listener
- [ ] ~~OptinMonster~~ (will not use this soon)

**Comment by AttackOnMorty** [comment]
Refer to the outcome issue: #89
