### ISSUE TITLE
✨ Home Page - Enhance SSW TV and Contact Us component

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#93]
Cc: @pierssinclairssw @adamcogan 

Hi @ozairashfaqueSSW 
  
### Pain

After comparing with the old website, there are a few enhancements that need to be made.

### Tasks

- [x] Add top border
- [x] Sydney Tab should be open default
- [x] Fix css breaking points for map 
- [x] Offices opening/closing on their time zones
- [x] Check the open tag logic in old website
- [x] Make map smaller
- [x] Add bottom padding

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/151283351-fa70c060-c47d-40c8-bf39-a6f14fb655c9.png)
**Figure: New Webiste - SSW TV and Contact Us component and offices open/close should be on their relevant time zones**

![image](https://user-images.githubusercontent.com/37203901/151283413-90137cd2-13fa-4284-97a2-e677fbf7be27.png)
**Figure: Old Website - SSW TV and Contact Us component**

Thanks!

**Comment by ozair-ashfaque** [comment]
Hi @AttackOnMorty,
  >Sydney Tab should be open defaultly
Not done - no solution found for defaultvalue, further investigation is required.

**Comment by ozair-ashfaque** [comment]
All done - see
![image](https://user-images.githubusercontent.com/96504411/153091382-ae51a007-952e-4a9c-bf91-3ff10723610d.png)
**Figure: Syndey office opens by default on page load, time zones added for office's open/close and map is responsive for all screens**
